{{- if .Values.sealedSecret }}
{{- if .Values.sealedSecret.enabled }}
{{- range $nameSuffix, $encryptedData := .Values.sealedSecret.files }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "application.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.stakater" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.sealedSecret.additionalLabels }}
{{ toYaml $.Values.sealedSecret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.sealedSecret.annotations }}
  annotations:
{{ toYaml $.Values.sealedSecret.annotations | indent 4 }}
{{- end }}
spec:
  encryptedData:
  {{- range $key, $value := .encryptedData }}
    {{ $key }}: {{ $value }}
  {{- end }}
  template:
    metadata:
      name: {{ template "application.name" $ }}-{{ $nameSuffix }}
      namespace: {{ template "application.namespace" $ }}
      {{- if $.Values.sealedSecret.annotations }}
      annotations:
     {{ toYaml $.Values.sealedSecret.annotations | indent 4 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
